services:
  nim-promethei-node1:
    image: promethei:latest
    environment:
      - PROMETHEI_LOG_LEVEL=${PROMETHEI_LOG_LEVEL:-TRACE}
      - PROMETHEI_METRICS=${PROMETHEI_METRICS:-false}
      - PROMETHEI_METRICS_ADDRESS=${PROMETHEI_METRICS_ADDRESS:-0.0.0.0}
      - PROMETHEI_METRICS_PORT=${PROMETHEI_METRICS_PORT:-8008}
      - PROMETHEI_DATA_DIR=${PROMETHEI_DATA_DIR:-/datadir}
      - PROMETHEI_LISTEN_ADDRS=${PROMETHEI_LISTEN_ADDRS:-/ip4/0.0.0.0/tcp/2345}
      - PROMETHEI_NAT=${PROMETHEI_NAT:-10.0.0.10}
      - PROMETHEI_DISC_PORT=${PROMETHEI_DISC_PORT:-8090}
      - PROMETHEI_NET_PRIVKEY=${PROMETHEI_NET_PRIVKEY:-key}
      # - PROMETHEI_BOOTSTRAP_NODE=${PROMETHEI_BOOTSTRAP_NODE}
      - PROMETHEI_MAX_PEERS=${PROMETHEI_MAX_PEERS:-160}
      - PROMETHEI_AGENT_STRING=${PROMETHEI_AGENT_STRING:-Promethei}
      - PROMETHEI_API_BINDADDR=${PROMETHEI_API_BINDADDR:-0.0.0.0}
      - PROMETHEI_API_PORT=${PROMETHEI_API_PORT:-8080}
      - PROMETHEI_REPO_KIND=${PROMETHEI_REPO_KIND:-fs}
      - PROMETHEI_STORAGE_QUOTA=${PROMETHEI_STORAGE_QUOTA:-8589934592}
      - PROMETHEI_BLOCK_TTL=${PROMETHEI_BLOCK_TTL:-0}
      # - PROMETHEI_BLOCK_MI=${PROMETHEI_BLOCK_MI}
      - PROMETHEI_BLOCK_MN=${PROMETHEI_BLOCK_MN:-1000}
      - PROMETHEI_CACHE_SIZE=${PROMETHEI_CACHE_SIZE:-0}
      - PROMETHEI_PERSISTENCE=${PROMETHEI_PERSISTENCE:-false}
      - PROMETHEI_ETH_PROVIDER=${PROMETHEI_ETH_PROVIDER:-ws://localhost:8545}
      # - PROMETHEI_ETH_ACCOUNT=${PROMETHEI_ETH_ACCOUNT}
      # - PROMETHEI_MARKETPLACE_ADDRESS=${PROMETHEI_MARKETPLACE_ADDRESS:-0x59b670e9fA9D0A427751Af201D676719a970857b}
      - PROMETHEI_VALIDATOR=${PROMETHEI_VALIDATOR:-false}
      - PROMETHEI_VALIDATOR_MAX_SLOTS=${PROMETHEI_VALIDATOR_MAX_SLOTS:-1000}
      - NAT_IP_AUTO=false
      - NAT_PUBLIC_IP_AUTO=https://ipinfo.io/ip
    ports:
      - 8080:8080/tcp # REST API
      - 8008:8008/tcp # Metrics
      - 2345:2345/tcp # libp2p
      - 8090:8090/udp # DHT discovery
    volumes:
      - ./datadir:/datadir:z
    networks:
      - promethei
networks:
  promethei:
    driver: bridge
