name: Reusable - CI

on:
  workflow_call:
    inputs:
      matrix:
        type: string
      nim_version:
        type: string
      rust_version:
        type: string
      cmake_version:
        type: string
      node_version:
        type: string

env:
  UNITTEST2_OUTPUT_LVL: VERBOSE # outputs which test is currently running

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(inputs.matrix) }}

    name: ${{ matrix.builder }}-${{ matrix.tests }}-${{ matrix.job_number }}
    runs-on: ${{ matrix.builder }}
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}

      - name: CI setup
        uses: ./.github/actions/ci-setup
        with:
          os: ${{ matrix.os }}
          nim_version: ${{ inputs.nim_version }}
          rust_version: ${{ inputs.rust_version }}
          cmake_version: ${{ inputs.cmake_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        if: matrix.tests == 'contract' || matrix.tests == 'integration' || matrix.tests == 'tools'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install nasm (Windows)
        if: runner.os == 'Windows'
        run: choco install nasm -y

      - name: Build
        run: nimble build

      - name: Unit tests
        if: matrix.tests == 'unittest'
        run: nimble test

      - name: Contract tests
        if: matrix.tests == 'contract'
        run: nimble testContracts

      - name: Integration tests
        if: matrix.tests == 'integration'
        env:
          PROMETHEI_INTEGRATION_TEST_INCLUDES: ${{ matrix.includes }}
        run: nimble testIntegration

      - name: Tools tests
        if: matrix.tests == 'tools'
        run: nimble testTools

      - name: Upload integration tests log files
        uses: actions/upload-artifact@v4
        if: always() && matrix.tests == 'integration'
        with:
          name: ${{ matrix.builder }}-${{ matrix.job_number }}-integration-tests-logs
          path: logs/testbed
          retention-days: 1

  status:
    if: always()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  || contains(needs.*.result, 'skipped') }}
        run: exit 1
