name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore: &paths-ignore
      - '**/*.md'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/ci-reusable.yml'
      - '!.github/workflows/actions/ci-setup/action.yml'
      - 'docker/**'
  pull_request:
    paths-ignore: *paths-ignore
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  nim_version:   2.2.6
  rust_version:  1.79.0
  cmake_version: 3.x
  node_version:  22

jobs:
  variables:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message || github.event.pull_request.title, '[release]') }}
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      nim_version: ${{ env.nim_version }}
      rust_version: ${{ env.rust_version }}
      cmake_version: ${{ env.cmake_version }}
      node_version: ${{ env.node_version }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Compute matrix
        id: matrix
        run: |
          echo 'matrix<<EOF' >> $GITHUB_OUTPUT
          tools/scripts/ci-job-matrix.sh >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  build:
    needs: variables
    uses: ./.github/workflows/ci-reusable.yml
    with:
      matrix: ${{ needs.variables.outputs.matrix }}
      nim_version:   ${{ needs.variables.outputs.nim_version }}
      rust_version:  ${{ needs.variables.outputs.rust_version }}
      cmake_version: ${{ needs.variables.outputs.cmake_version }}
      node_version:  ${{ needs.variables.outputs.node_version }}

  linting:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && !contains(github.event.head_commit.message || github.event.pull_request.title, '[release]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Check `nph` formatting
        uses: arnetheduck/nph-action@v1
        with:
          version: 0.6.1
          options: "promethei/ tests/"
          fail: true
          suggest: false
