name: Deploy on network

on:
  workflow_dispatch:
    inputs:
      network:
        description: Network deploy on
        required: true
        default: devnet
        options:
          - devnet
          - testnet
        type: choice
      promethei_image:
        description: durabilitylabs/nim-promethei-node:latest-dist-tests
        required: true
        type: string
  workflow_call:
    inputs:
      network:
        description: Network deploy on
        required: true
        type: string
      promethei_image:
        description: durabilitylabs/nim-promethei-node:latest-dist-tests
        required: true
        type: string

env:
  NETWORK: ${{ inputs.network }}
  KUBE_VERSION: v1.33.1
  PROMETHEI_IMAGE: ${{ inputs.promethei_image }}
  PROMETHEI_STORAGE_LABEL: promethei-storage
  PROMETHEI_VALIDATOR_LABEL: promethei-validator
  CONTRACTS_REPOSITORY: promethei-contracts
  CONTRACTS_DEPLOYMENT_WORKFLOW: devnet-contracts.yml
  CONFIG_REPOSITORY: promethei-config
  CONFIG_REPOSITORY_BRANCH: main
  CONFIG_ENDPOINT: https://config.archivist.storage

jobs:
  compute-variables:
    name: Compute variables
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.variables.outputs.app_version }}
      app_revision: ${{ steps.variables.outputs.app_revision }}
      contracts_revision: ${{ steps.variables.outputs.contracts_revision }}
      contracts_ref: ${{ steps.variables.outputs.contracts_ref }}
      contracts_deploy: ${{ steps.variables.outputs.contracts_deploy }}
      bootstrap_nodes_update: ${{ steps.variables.outputs.bootstrap_nodes_update }}
      autoclient_nodes_update: ${{ steps.variables.outputs.autoclient_nodes_update }}
      cluster_tools_update: ${{ steps.variables.outputs.cluster_tools_update }}
      secrets_prefix: ${{ steps.case.outputs.secrets_prefix }}
    steps:
      - name: Set variables from a Docker image
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            docker pull ${{ env.PROMETHEI_IMAGE }}
            echo "ref_sha=$(docker inspect ${{ env.PROMETHEI_IMAGE }} --format='{{index .Config.Labels "org.opencontainers.image.revision"}}')" >> $GITHUB_ENV
            echo "image_version=$(docker inspect ${{ env.PROMETHEI_IMAGE }} --format='{{index .Config.Labels "org.opencontainers.image.version"}}')" >> $GITHUB_ENV
          else
            echo "ref_sha=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          submodules: recursive
          ref: ${{ env.ref_sha }}

      - name: Secrets prefix
        id: case
        run: echo "secrets_prefix=${NETWORK^^}" >> $GITHUB_OUTPUT

      - name: Secrets to env
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          include: ${{ steps.case.outputs.secrets_prefix }}_SSH_HOST_BOOTSTRAP_*, ${{ steps.case.outputs.secrets_prefix }}_SSH_HOST_AUTOCLIENT_*

      - name: Set outputs
        id: variables
        run: |
          # Versions
          app_revision=$(git rev-parse --short HEAD)
          echo "app_revision=${app_revision}" >> $GITHUB_OUTPUT
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            if [[ "${{ env.image_version }}" =~ [a-z]?[0-9]+\.[0-9]+\.[0-9] ]]; then
              echo "app_version=${{ env.image_version }}" >> $GITHUB_OUTPUT
            else
              echo "app_version=${app_revision}" >> $GITHUB_OUTPUT
            fi
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "app_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "app_version=${app_revision}" >> $GITHUB_OUTPUT
          fi

          # Contracts
          contracts_deployed=$(curl -s ${{ env.CONFIG_ENDPOINT }}/${{ env.NETWORK }}.json | jq -r '.promethei[].contracts')
          contracts_submodule=$(git rev-parse --short HEAD:vendor/${{ env.CONTRACTS_REPOSITORY }})
          echo "contracts_revision=${contracts_submodule}" >> $GITHUB_OUTPUT
          echo "contracts_ref=$(git rev-parse HEAD:vendor/${{ env.CONTRACTS_REPOSITORY }})" >> $GITHUB_OUTPUT

          # Check if contracts-deploy is needed - skip for != devnet
          if [[ "${{ env.NETWORK }}" != "devnet" ]]; then
            echo "contracts_deploy=false" >> $GITHUB_OUTPUT
          else
            if [[ "${contracts_deployed}" != "${contracts_submodule}" ]]; then
              echo "Contracts revision mismatch: deployed=${contracts_deployed} / submodule=${contracts_submodule}"
              contracts_deploy="true"
              echo "contracts_deploy=${contracts_deploy}" >> $GITHUB_OUTPUT
            else
              echo "Contracts revision is the same: deployed=${contracts_deployed} / submodule=${contracts_submodule}"
            fi
          fi

          # Check if we have bootstrap and autoclient nodes defined for a network
          if [[ $(env | grep -c ${{ steps.case.outputs.secrets_prefix }}_SSH_HOST_BOOTSTRAP_ || true) -gt 0 ]]; then echo "bootstrap_nodes_update=true" >> $GITHUB_OUTPUT; fi
          if [[ $(env | grep -c ${{ steps.case.outputs.secrets_prefix }}_SSH_HOST_AUTOCLIENT_ || true) -gt 0 ]]; then echo "autoclient_nodes_update=true" >> $GITHUB_OUTPUT; fi

          # Check if cluster-tools update is needed - forcibly for != devnet
          if [[ "${{ env.NETWORK }}" != "devnet" ]]; then
            echo "cluster_tools_update=true" >> $GITHUB_OUTPUT
          else
            if [[ "${contracts_deploy}" == "true" ]]; then
              echo "cluster_tools_update=true" >> $GITHUB_OUTPUT
            fi
          fi

  contracts-deploy:
    name: Contracts deploy
    runs-on: ubuntu-latest
    needs: compute-variables
    if: needs.compute-variables.outputs.contracts_deploy == 'true'
    steps:
      - name: Create access token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          repositories: ${{ env.CONTRACTS_REPOSITORY }}

      - name: Deploy smart contracts
        uses: the-actions-org/workflow-dispatch@v4
        with:
          repo: ${{ github.repository_owner }}/${{ env.CONTRACTS_REPOSITORY }}
          workflow: ${{ env.CONTRACTS_DEPLOYMENT_WORKFLOW }}
          token: ${{ steps.app-token.outputs.token }}
          wait-for-completion-timeout: 30m
          wait-for-completion-interval: 10s
          inputs: '{ "network": "${{ env.NETWORK }}", "contracts_ref": "${{ needs.compute-variables.outputs.contracts_ref }}" }'

  bootstrap-nodes:
    name: Bootstrap nodes
    runs-on: ubuntu-latest
    needs: [compute-variables, contracts-deploy]
    if: ${{ !(failure() || cancelled()) && needs.compute-variables.outputs.bootstrap_nodes_update == 'true' }}
    steps:
      - name: Secrets to env
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          include: ${{ needs.compute-variables.outputs.secrets_prefix }}_SSH_HOST_BOOTSTRAP_*

      - name: Compute hosts
        run: |
          for host in ${!${{ needs.compute-variables.outputs.secrets_prefix }}_SSH_HOST_BOOTSTRAP_*}; do
            current_hosts="${!host}"
            if [[ -z "${SSH_HOST}" ]]; then
              SSH_HOST="${current_hosts}"
            else
              SSH_HOST="${SSH_HOST},${current_hosts}"
            fi
          done
          echo "SSH_HOST=${SSH_HOST}" >> $GITHUB_ENV

      - name: Nodes update
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ secrets[format('{0}_SSH_USERNAME', inputs.network)] }}
          key: ${{ secrets[format('{0}_SSH_KEY', inputs.network)] }}
          script: ${{ env.PROMETHEI_IMAGE }}

  cluster-nodes:
    name: Cluster nodes
    runs-on: ubuntu-latest
    needs: bootstrap-nodes
    if: ${{ !(failure() || cancelled()) }}
    env:
      PROMETHEI_NAMESPACE: ${{ secrets[format('{0}_KUBE_NAMESPACE_PROMETHEI', inputs.network)] }}
    steps:
      - name: Kubectl - Install ${{ env.KUBE_VERSION }}
        uses: azure/setup-kubectl@v4
        with:
          version: ${{ env.KUBE_VERSION }}

      - name: Kubectl - Kubeconfig
        run: |
          mkdir -p "${HOME}"/.kube
          echo "${{ env.KUBE_CONFIG }}" | base64 -d > "${HOME}"/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets[format('{0}_KUBE_CONFIG', inputs.network)] }}

      - name: Storage nodes - Update
        run: |
          label="app.kubernetes.io/instance=${{ env.PROMETHEI_STORAGE_LABEL }}"
          statefulsets=$(kubectl get statefulset -n "${{ env.PROMETHEI_NAMESPACE }}" -l "${label}" --ignore-not-found --no-headers -o custom-columns=":metadata.name")
          echo "storage_nodes=$(wc -w <<< ${statefulsets})" >> $GITHUB_ENV
          for statefulset in ${statefulsets}; do
            kubectl -n "${{ env.PROMETHEI_NAMESPACE }}" patch statefulset "${statefulset}" \
              --patch '{"spec": {"template": {"spec":{"containers":[{"name": "promethei", "image":"${{ env.PROMETHEI_IMAGE }}"}]}}}}'
            sleep 10
          done

      - name: Validator nodes - Update
        run: |
          label="app.kubernetes.io/instance=${{ env.PROMETHEI_VALIDATOR_LABEL }}"
          statefulsets=$(kubectl get statefulset -n "${{ env.PROMETHEI_NAMESPACE }}" -l "${label}" --ignore-not-found --no-headers -o custom-columns=":metadata.name")
          echo "validator_nodes=$(wc -w <<< ${statefulsets})" >> $GITHUB_ENV
          for statefulset in ${statefulsets}; do
            kubectl -n "${{ env.PROMETHEI_NAMESPACE }}" patch statefulset "${statefulset}" \
              --patch '{"spec": {"template": {"spec":{"containers":[{"name": "promethei", "image":"${{ env.PROMETHEI_IMAGE }}"}]}}}}'
            sleep 10
          done

      - name: Storage nodes - Status
        run: |
          WAIT=900
          SECONDS=0
          sleep=1
          pod_prefix="${{ env.PROMETHEI_STORAGE_LABEL }}"
          if [[ ${{ env.storage_nodes }} -ge 0 ]]; then
            for instance in {1..${{ env.storage_nodes }}}; do
              while (( SECONDS < WAIT )); do
                pod=${pod_prefix}-${instance}-1
                phase=$(kubectl get pod "${pod}" -n "${{ env.PROMETHEI_NAMESPACE }}" -o jsonpath='{.status.phase}')
                if [[ "${phase}" == "Running" ]]; then
                  echo "Pod ${pod} is in the ${phase} state"
                  break
                else
                  echo "Pod ${pod} is in the ${phase} state - Check in ${sleep} second(s) / $((WAIT - SECONDS))"
                fi
                sleep "${sleep}"
              done
            done
          fi
          if [[ "${phase}" != "Running" ]]; then
            echo "Pod ${pod} is in the ${phase} state"
            exit 1
          fi

      - name: Validator nodes - Status
        run: |
          WAIT=900
          SECONDS=0
          sleep=1
          pod_prefix="${{ env.PROMETHEI_VALIDATOR_LABEL }}"
          if [[ ${{ env.validator_nodes }} -ge 0 ]]; then
            for instance in {1..${{ env.validator_nodes }}}; do
              while (( SECONDS < WAIT )); do
                pod=${pod_prefix}-${instance}-1
                phase=$(kubectl get pod "${pod}" -n "${{ env.PROMETHEI_NAMESPACE }}" -o jsonpath='{.status.phase}')
                if [[ "${phase}" == "Running" ]]; then
                  echo "Pod ${pod} is in the ${phase} state"
                  break
                else
                  echo "Pod ${pod} is in the ${phase} state - Check in ${sleep} second(s) / $((WAIT - SECONDS))"
                fi
                sleep "${sleep}"
              done
            done
          fi
          if [[ "${phase}" != "Running" ]]; then
            echo "Pod ${pod} is in the ${phase} state"
            exit 1
          fi

  cluster-tools:
    name: Cluster tools
    runs-on: ubuntu-latest
    needs: [compute-variables, cluster-nodes]
    if: ${{ !(failure() || cancelled()) && needs.compute-variables.outputs.cluster_tools_update == 'true' }}
    env:
      TOOLS_NAMESPACE: ${{ secrets[format('{0}_KUBE_NAMESPACE_TOOLS', inputs.network)] }}
    steps:
      - name: Kubectl - Install ${{ env.KUBE_VERSION }}
        uses: azure/setup-kubectl@v4
        with:
          version: ${{ env.KUBE_VERSION }}

      - name: Kubectl - Kubeconfig
        run: |
          mkdir -p "${HOME}"/.kube
          echo "${{ env.KUBE_CONFIG }}" | base64 -d > "${HOME}"/.kube/config
        env:
          KUBE_CONFIG: ${{ secrets[format('{0}_KUBE_CONFIG', inputs.network)] }}

      - name: Tools - Update
        run: |
          crawler_pod=$(kubectl get pod -n "${{ env.TOOLS_NAMESPACE }}" -l 'app.kubernetes.io/name=crawler' -ojsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
          discordbot_pod=$(kubectl get pod -n "${{ env.TOOLS_NAMESPACE }}" -l 'app=discordbot' -ojsonpath='{.items[0].metadata.name}' 2>/dev/null || true)

          for pod in "${crawler_pod}" "${discordbot_pod}"; do
            if [[ -n "${pod}" ]]; then
              kubectl delete pod -n "${{ env.TOOLS_NAMESPACE }}" "${pod}" --grace-period=30
            fi
          done

      - name: Tools - Status
        run: |
          WAIT=300
          SECONDS=0
          sleep=1
          crawler_pod=$(kubectl get pod -n "${{ env.TOOLS_NAMESPACE }}" -l 'app.kubernetes.io/name=crawler' -ojsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
          discordbot_pod=$(kubectl get pod -n "${{ env.TOOLS_NAMESPACE }}" -l 'app=discordbot' -ojsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
          for pod in "${crawler_pod}" "${discordbot_pod}"; do
            if [[ -n "${pod}" ]]; then
              while (( SECONDS < WAIT )); do
                phase=$(kubectl get pod "${pod}" -n "${{ env.TOOLS_NAMESPACE }}" -o jsonpath='{.status.phase}')
                if [[ "${phase}" == "Running" ]]; then
                  echo "Pod ${pod} is in the ${phase} state"
                  break
                else
                  echo "Pod ${pod} is in the ${phase} state - Check in ${sleep} second(s) / $((WAIT - SECONDS))"
                fi
                sleep "${sleep}"
              done
            fi
          done
          if [[ "${phase}" != "Running" ]]; then
            echo "Pod ${pod} is in the ${phase} state"
            exit 1
          fi

  config-update:
    name: Config update
    runs-on: ubuntu-latest
    needs: [compute-variables, cluster-tools]
    if: ${{ !(failure() || cancelled()) }}
    steps:
      - name: Create access token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ env.CONFIG_REPOSITORY }}

      - name: Checkout config repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository_owner }}/${{ env.CONFIG_REPOSITORY }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Checkout config repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository_owner }}/${{ env.CONFIG_REPOSITORY }}
          ref: ${{ env.CONFIG_REPOSITORY_BRANCH }}

      - name: Config update
        run: |
          # Variables
          config="${{ env.NETWORK }}.json"
          config_updated="${{ env.NETWORK }}-updated.json"

          # Functions
          rename_config() {
            mv "${config_updated}" "${config}"
          }

          # .latest
          jq -r '.latest |= "${{ needs.compute-variables.outputs.app_version }}"' "${config}" > "${config_updated}" && rename_config

          # .promethei.version
          jq -r '.promethei[].version |= "${{ needs.compute-variables.outputs.app_version }}"' "${config}" > "${config_updated}" && rename_config

          # .promethei.revision
          jq -r '.promethei[].revision |= "${{ needs.compute-variables.outputs.app_revision }}"' "${config}" > "${config_updated}" && rename_config

          # .promethei.contracts
          jq -r '.promethei[].contracts |= "${{ needs.compute-variables.outputs.contracts_revision }}"' "${config}" > "${config_updated}" && rename_config

          # .sprs
          jq -r '.sprs[].supportedVersions[] |= "${{ needs.compute-variables.outputs.app_version }}"' "${config}" > "${config_updated}" && rename_config

          # .marketplace
          jq -r '.marketplace[].supportedVersions[] |= "${{ needs.compute-variables.outputs.app_version }}"' "${config}" > "${config_updated}" && rename_config

          # .team.nodes.category.versions.version
          jq -r '.team.nodes[].versions[].version |= "${{ needs.compute-variables.outputs.app_version }}"' "${config}" > "${config_updated}" && rename_config

      - name: Commit updated config
        uses: planetscale/ghcommit-action@v0.2.18
        with:
          commit_message: "chore(${{ env.NETWORK }}): promethei updated\n${{ github.actor }}\n${{ github.ref_type }}: ${{ github.ref_name }}\n${{ github.event_name }}: ${{ github.repository }}\n${{ github.event.head_commit.message || 'triggered manually' }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          repo: ${{ github.repository_owner }}/${{ env.CONFIG_REPOSITORY }}
          branch: ${{ env.CONFIG_REPOSITORY_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  autoclient-nodes:
    name: Autoclient nodes
    runs-on: ubuntu-latest
    needs: [compute-variables, config-update]
    if: ${{ !(failure() || cancelled()) && needs.compute-variables.outputs.autoclient_nodes_update == 'true' }}
    steps:
      - name: Secrets to env
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          include: ${{ needs.compute-variables.outputs.secrets_prefix }}_SSH_HOST_AUTOCLIENT_*

      - name: Compute hosts
        run: |
          for host in ${!${{ needs.compute-variables.outputs.secrets_prefix }}_SSH_HOST_AUTOCLIENT_*}; do
            current_hosts="${!host}"
            if [[ -z "${SSH_HOST}" ]]; then
              SSH_HOST="${current_hosts}"
            else
              SSH_HOST="${SSH_HOST},${current_hosts}"
            fi
          done
          echo "SSH_HOST=${SSH_HOST}" >> $GITHUB_ENV

      - name: Nodes update
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ secrets[format('{0}_SSH_USERNAME', inputs.network)] }}
          key: ${{ secrets[format('{0}_SSH_KEY', inputs.network)] }}
          script: ${{ env.PROMETHEI_IMAGE }}

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [compute-variables, contracts-deploy, bootstrap-nodes, cluster-nodes, cluster-tools, config-update, autoclient-nodes]
    if: always()
    steps:
      - name: Emojify jobs status
        id: emojify
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            let status = '';
            Object.entries(${{ toJSON(needs) }}).forEach(([key, value]) => {
              switch(value.result) {
                case "success":
                  Object.assign(value, {"emoji": ":green_circle:"});
                  break
                case "skipped":
                  Object.assign(value, {"emoji": ":white_circle:"});
                  break
                case "cancelled":
                  Object.assign(value, {"emoji": ":grey_exclamation:"});
                  break
                case "failure":
                  Object.assign(value, {"emoji": ":red_circle:"});
              }
              status += `- ${value.emoji}  ${key}\n`;
              core.setOutput("status", status);
            });

      - name: Deployment jobs status
        if: always()
        id: jobs
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}"  == "true" ]]; then
            echo "status=:x:" >> $GITHUB_ENV
            exit 1
          else
            echo "status=:white_check_mark:" >> $GITHUB_ENV
          fi
          if [[ "${{ env.NETWORK}}" != "devnet" ]]; then echo "network_mark=:bulb:" >> $GITHUB_ENV; fi

      - name: Discord
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          title: "${{ env.status }} **${{ env.NETWORK }}** - auto deploy ${{ env.network_mark }}"
          description: |
            ```yaml
            - app version:        ${{ needs.compute-variables.outputs.app_version }}
            - app revision:       ${{ needs.compute-variables.outputs.app_revision }}
            - contracts revision: ${{ needs.compute-variables.outputs.contracts_revision }}
            ${{ env.PROMETHEI_IMAGE }}
            ```
            ${{ steps.emojify.outputs.status }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          noprefix: true
