name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/release.yml'
      - 'docker/**'
  workflow_dispatch:

env:
  nim_version:   2.2.6
  rust_version:  1.79.0
  cmake_version: 3.x
  artifacts_base: promethei
  promethei_binary_base: promethei
  cirdl_binary_base: cirdl
  setup_binary_base: setup
  build_dir: build
  nim_flags: '-d:release -d:nimleopard_portable_build'
  windows_libs: 'libgcc_s_seh-1.dll libwinpthread-1.dll'

jobs:
  # Matrix
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - name: Compute matrix
      id: matrix
      uses: fabiocaccamo/create-matrix-action@v5
      with:
        matrix: |
          os {linux},   cpu {amd64}, builder {ubuntu-22.04},     nim_version {${{ env.nim_version }}}
          os {linux},   cpu {arm64}, builder {ubuntu-22.04-arm}, nim_version {${{ env.nim_version }}}
          os {macos},   cpu {amd64}, builder {macos-15-intel},   nim_version {${{ env.nim_version }}}
          os {macos},   cpu {arm64}, builder {macos-15},         nim_version {${{ env.nim_version }}}
          os {windows}, cpu {amd64}, builder {windows-latest}  , nim_version {${{ env.nim_version }}}

  # Build
  build:
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.matrix.outputs.matrix)}}

    name: ${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.nim_version }}
    runs-on: ${{ matrix.builder }}
    timeout-minutes: 80
    steps:
      - name: Release - Show linux runner info
        if: matrix.os == 'linux'
        run: |
          curl -sLO https://raw.githubusercontent.com/HenrikBengtsson/x86-64-level/main/x86-64-level
          chmod ugo+x x86-64-level
          ./x86-64-level --verbose || true

          for run in "lscpu" "lshw -class processor" "dmidecode -t processor"; do
            echo -e "\n\n";
            echo "${run}";
            eval sudo ${run};
          done

      - name: Release - Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Release - CI setup
        uses: ./.github/actions/ci-setup
        with:
          nim_version: ${{ env.nim_version }}
          rust_version: ${{ env.rust_version }}
          cmake_version: ${{ env.cmake_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release - Compute variables
        shell: bash
        run: |
          # Binary names
          case ${{ matrix.os }} in
            linux*)   os_name="linux"   ;;
            macos*)   os_name="darwin"  ;;
            windows*) os_name="windows" ;;
          esac
          github_ref_name="${GITHUB_REF_NAME/\//-}"
          promethei_binary="${{ env.promethei_binary_base }}-${github_ref_name}-${os_name}-${{ matrix.cpu }}"
          cirdl_binary="${{ env.cirdl_binary_base }}-${github_ref_name}-${os_name}-${{ matrix.cpu }}"
          setup_binary="${{ env.setup_binary_base }}-${github_ref_name}-${os_name}-${{ matrix.cpu }}"
          if [[ ${os_name} == "windows" ]]; then
            promethei_binary="${promethei_binary}.exe"
            cirdl_binary="${cirdl_binary}.exe"
            setup_binary="${setup_binary}.exe"
          fi
          echo "promethei_binary=${promethei_binary}" >> $GITHUB_ENV
          echo "cirdl_binary=${cirdl_binary}" >> $GITHUB_ENV
          echo "setup_binary=${setup_binary}" >> $GITHUB_ENV

          # Nim flags
          if [[ "${{ matrix.os }}" == "windows" ]]; then
            echo "nim_flags=-d:chronicles_colors=off ${{ env.nim_flags }}" >> $GITHUB_ENV
          fi

      - name: Release - Build
        run: |
          nimble build ${{ env.nim_flags }}
          mv ${{ env.build_dir }}/${{ env.promethei_binary_base }}* ${{ env.build_dir }}/${{ env.promethei_binary }}
          mv ${{ env.build_dir }}/tools/${{ env.cirdl_binary_base }}/${{ env.cirdl_binary_base }}* ${{ env.build_dir }}/${{ env.cirdl_binary }}
          mv ${{ env.build_dir }}/tools/${{ env.setup_binary_base }}/${{ env.setup_binary_base }}* ${{ env.build_dir }}/${{ env.setup_binary }}

      - name: Release - Windows libraries
        if: matrix.os == 'windows'
        shell: bash
        run: |
          MINGW_PATH=$(awk -F ':' '/mingw64/ {print $1}' <<< $PATH)
          for lib in ${{ env.windows_libs }}; do
            cp -v "${MINGW_PATH}/${lib}" "${{ env.build_dir }}"
          done

      - name: Release - Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: release-${{ env.promethei_binary }}
          path: ${{ env.build_dir }}/*
          retention-days: 30

  # Release
  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()
    steps:
      - name: Release - Download binaries
        uses: actions/download-artifact@v6
        with:
          pattern: release*
          merge-multiple: true
          path: /tmp/release

      - name: Release - Compress and checksum
        run: |
          cd /tmp/release
          checksum() {
            archive="${1}"
            sha256sum "${archive}" > "${archive}.sha256"
          }

          # Compress and prepare
          for file in ${{ env.promethei_binary_base }}*; do
            if [[ "${file}" == *".exe"* ]]; then

              # Windows - binaries and libs
              file="${file%.*}"
              subset="${file//${{ env.promethei_binary_base }}-/}"
              archive="${{ env.artifacts_base }}-${subset}.zip"
              binaries=""
              for binary in *-${subset}.exe; do
                binary_packed="${binary//-${subset}/}"
                mv "${binary}" "${binary_packed}"
                binaries+=" ${binary_packed}"
              done
              zip "${archive}" ${binaries} ${{ env.windows_libs }}
              rm -f ${binaries} ${{ env.windows_libs }}
              checksum "${archive}"
            else

              # Linux/macOS binaries
              subset="${file//${{ env.promethei_binary_base }}-/}"
              archive="${{ env.artifacts_base }}-${subset}.tar.gz"
              chmod 755 *-${subset}
              binaries=""
              for binary in *-${subset}; do
                binary_packed="${binary//-${subset}/}"
                mv "${binary}" "${binary_packed}"
                binaries+=" ${binary_packed}"
              done
              tar cfz "${archive}" ${binaries}
              rm -f ${binaries}
              checksum "${archive}"
            fi
          done

      - name: Release - Upload compressed artifacts and checksums
        uses: actions/upload-artifact@v5
        with:
          name: archives-and-checksums
          path: /tmp/release/
          retention-days: 30

      - name: Release - Upload to the cloud
        env:
          s3_endpoint: ${{ secrets.S3_ENDPOINT }}
          s3_bucket: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          # Variables
          branch="${GITHUB_REF_NAME/\//-}"
          folder="/tmp/release"

          # Tagged releases
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            aws s3 cp --recursive "${folder}" s3://${{ env.s3_bucket }}/releases/${branch} --endpoint-url ${{ env.s3_endpoint }}
            echo "${branch}" > "${folder}"/latest
            aws s3 cp "${folder}"/latest s3://${{ env.s3_bucket }}/releases/latest --endpoint-url ${{ env.s3_endpoint }}
            rm -f "${folder}"/latest

          # master branch
          elif [[ "${branch}" == "${{ github.event.repository.default_branch }}" ]]; then
            aws s3 cp --recursive "${folder}" s3://${{ env.s3_bucket }}/${branch} --endpoint-url ${{ env.s3_endpoint }}

          # Custom branch
          else
            aws s3 cp --recursive "${folder}" s3://${{ env.s3_bucket }}/branches/${branch} --endpoint-url ${{ env.s3_endpoint }}
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            /tmp/release/*
          make_latest: true
