global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nim-promethei-nodes'
    static_configs:
      - targets: ['localhost:10008']
        labels:
          node: 'e2e-node1'
          namespace: 'promethei'
          pod: 'nim-promethei-node1'
      - targets: ['localhost:10009']
        labels:
          node: 'e2e-node2'
          namespace: 'promethei'
          pod: 'nim-promethei-node2'
      - targets: ['localhost:10010']
        labels:
          node: 'e2e-node3'
          namespace: 'promethei'
          pod: 'nim-promethei-node3'
      - targets: ['localhost:10011']
        labels:
          node: 'e2e-node4'
          namespace: 'promethei'
          pod: 'nim-promethei-node4'
      - targets: ['localhost:10012']
        labels:
          node: 'e2e-node5'
          namespace: 'promethei'
          pod: 'nim-promethei-node5'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          node: 'e2e-host'
          namespace: 'promethei'
          pod: 'node-exporter'
